import { mkdir, readFile, writeFile, readdir, unlink, watch } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";
import { discoverContent } from "../src/content/discovery.ts";
import { compileArticle } from "../src/content/compile.ts";
import { isRenderable } from "../src/content/catalog.ts";

const repository = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const root = path.join(repository, "content");
const output = path.join(repository, "src", "content", ".generated");
async function writeChanged(file: string, value: string) {
  if (await readFile(file, "utf8").catch(() => "") !== value) await writeFile(file, value);
}
export async function generateContent(fixtures = false) {
  const { documents, catalog } = await discoverContent(root);
  // Validate and compile all documents, including drafts, before touching generated output.
  const compiled = [];
  for (const doc of documents) {
    const article = catalog.articles.find(item => item.id === doc.metadata.id)!;
    compiled.push({ article, ...await compileArticle(doc.body, article, catalog, doc.file) });
  }
  const visible = compiled.filter(item => isRenderable(item.article, fixtures));
  await mkdir(output, { recursive: true });
  const keep = new Set(["index.ts"]);
  for (const item of visible) {
    keep.add(`article-${item.article.id}.js`); keep.add(`article-${item.article.id}.d.ts`);
    await writeChanged(path.join(output, `article-${item.article.id}.js`), item.code);
    await writeChanged(path.join(output, `article-${item.article.id}.d.ts`), 'import type { ComponentType } from "react";\nimport type { MDXProps } from "mdx/types";\ndeclare const Content: ComponentType<MDXProps>;\nexport default Content;\n');
  }
  const index = `// Generated by scripts/content.mts. Do not edit. Server-only delivery data.\nimport type { ArticleHeading, ContentCatalog } from "../contracts";\nimport type { ComponentType } from "react";\nimport type { MDXProps } from "mdx/types";\nexport const catalog: ContentCatalog = ${JSON.stringify(catalog, null, 2)};\nexport const fixturesEnabled = ${fixtures};\nexport const articleHeadings: Record<string, ArticleHeading[]> = ${JSON.stringify(Object.fromEntries(visible.map(item => [item.article.id, item.headings])))};\nexport const embeddedCases: Record<string, string[]> = ${JSON.stringify(Object.fromEntries(visible.map(item => [item.article.id, item.caseIds])))};\nexport const loaders: Record<string, () => Promise<{ default: ComponentType<MDXProps> }>> = {\n${visible.map(item => `  ${JSON.stringify(item.article.id)}: () => import("./article-${item.article.id}.js"),`).join("\n")}\n};\n`;
  await writeChanged(path.join(output, "index.ts"), index);
  // Only individual generated files within this fixed directory are removed; no recursive deletion.
  for (const file of await readdir(output)) if (!keep.has(file) && /^[a-zA-Z0-9-]+\.(?:js|d\.ts)$/.test(file)) await unlink(path.join(output, file));
  console.log(`Content: validated ${compiled.length}; ${visible.length} routable (${fixtures ? "fixture preview enabled" : "publication only"}).`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const dev = process.argv.includes("--dev");
  await generateContent(dev || process.argv.includes("--fixtures"));
  if (dev) {
    const next = spawn(process.execPath, [path.join(repository, "node_modules/next/dist/bin/next"), "dev", ...process.argv.slice(2).filter(arg => arg !== "--dev")], { cwd: repository, stdio: "inherit" });
    const controller = new AbortController();
    next.on("exit", code => { controller.abort(); process.exitCode = code ?? 1; });
    for (const signal of ["SIGINT", "SIGTERM"] as const) process.on(signal, () => { controller.abort(); next.kill(signal); });
    try {
      for await (const event of watch(root, { recursive: true, signal: controller.signal })) {
        if (!event.filename || !/\.(mdx|json)$/.test(String(event.filename))) continue;
        try { await generateContent(true); }
        catch (error) {
          console.error(error);
          // Fail closed: invalidate the delivery entry instead of serving stale successful content.
          await writeChanged(path.join(output, "index.ts"), `import type { ArticleHeading, ContentCatalog } from "../contracts";\nimport type { ComponentType } from "react";\nimport type { MDXProps } from "mdx/types";\nthrow new Error(${JSON.stringify(String(error))});\nexport const catalog: ContentCatalog = { articles: [], sources: [], knowledge: [], cases: [] };\nexport const fixturesEnabled = false;\nexport const articleHeadings: Record<string, ArticleHeading[]> = {};\nexport const embeddedCases: Record<string, string[]> = {};\nexport const loaders: Record<string, () => Promise<{ default: ComponentType<MDXProps> }>> = {};\n`);
        }
      }
    } catch (error) { if (!controller.signal.aborted) throw error; }
  }
}
